version: '3.8'

services:
  backend:
    build: ./example-backend
    ports:
    - 8080:8080
    container_name: backend-example
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  
  frontend:
    build: ./example-frontend
    ports:
    - 5000:5000
    container_name: frontend-example
  
  redis:
    image: redis:latest
  
  db:
    image: postgres:13.2-alpine
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    container_name: db
